language: python
before_script:
  - git clone https://github.com/micropython/micropython.git
  - cd micropython/unix
  - make axtls
  - make
  - ./micropython -m upip install micropython-unittest
  - cp ./micropython ../../
script:
  - ./micropython -m test-testsuite
