language: python
before_script:
  - git clone https://github.com/micropython/micropython.git
  - mv micropython micropython-dev
  - cd micropython-dev/unix
  - make axtls
  - make
  - ./micropython -m upip install micropython-unittest
  - cp ./micropython ../../
  - cd ../../
script:
  - ./micropython -m test-testsuite
